DROP DATABASE IF EXISTS shoudusse_ERP;
CREATE DATABASE IF NOT EXISTS shoudusse_ERP;
USE shoudusse_ERP;
SOURCE  C:/wamp64/www/ERP/SQL/Tables/Utilisateurs.sql;
select 'Table Utilisateurs OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/Groupes.sql;
select 'Table Groupes OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/UtilisateursGroupes.sql;
select 'Table UtilisateursGroupes OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/Modules.sql;
select 'Table Modules OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/Fonctionnalitees.sql;
select 'Table Fonctionnalitees OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/Droits.sql;
select 'Table Droits OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/Fournisseurs.sql;
select 'Table Fournisseurs OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/Articles.sql;
select 'Table Articles OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/RefAnnexesArticles.sql;
select 'Table RefAnnexesArticles OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/PhotosArticles.sql;
select 'Table PhotosArticles OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/ArticlesFournisseurs.sql;
select 'Table ArticlesFournisseurs OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/DepartementsProduits.sql;
select 'Table DepartementsProduits OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/FamillesArticles.sql;
select 'Table FamillesArticles OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/SousFamillesArticles.sql;
select 'Table SousFamillesArticles OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/Unites.sql;
select 'Table Unites  OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/ConversionsUnites.sql;
select 'Table ConversionsUnites  OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/Etablissements.sql;
select 'Table Etablissments OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/Depots.sql;
select 'Table Depots OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/PositionsStockage.sql;
select 'Table PositionStockage OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/AdressesFournisseurs.sql;
select 'Table Adresses OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/RefAnnexesFournisseurs.sql;
select 'Table Adresses OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/CorrespondantsFournisseurs.sql;
select 'Table CorrespondantsFournisseurs OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/MoyensContactsFournisseurs.sql;
select 'Table MoyensContactsFournisseurs OK';
SOURCE  C:/wamp64/www/ERP/SQL/Tables/HistoMouvementsStocks.sql;
select 'Table HistoMouvementsStocks OK';
SHOW TABLES;
select '--- Fin du script ---';