CREATE TABLE IF NOT EXISTS SousFamillesArticles (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	libelle VARCHAR(60),
	idFamille INT NOT NULL,
	UNIQUE(libelle),
	PRIMARY KEY(id),
	FOREIGN KEY (idFamille) REFERENCES Familles(id)
)
;